apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: python-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
