replicaCount: 2

image:
  repository: ghcr.io/pravinmoreone-ux/pathnex-python-app
  tag: 3a13cca92ba7a1548bcaa7cb9cd6e1216714838e
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

containerPort: 8000
