name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    name: Terraform Format and Validate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::263824391433:role/GitHubActions-Terraform-Role
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Convert Terraform Plan to JSON
        run: terraform show -json tfplan > tfplan.json

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa

      - name: Run OPA Policy Check
        run: |
          result=$(./opa eval \
            --data policies/terraform.rego \
            --input tfplan.json \
            --format=json \
            "data.terraform.deny")

          echo "$result"

          violations=$(echo "$result" | jq -r '.result[0].expressions[0].value | length')

          if [ "$violations" -gt 0 ]; then
            echo "OPA policy violations detected."
            exit 1
          fi

          echo "OPA policy check passed."